name: Create Release PR

on:
  push:
    branches: [ "main" ]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cocogitto release
        id: release
        uses: oknozor/cocogitto-action@v3
        with:
          release: true

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} > CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Release ${{ steps.release.outputs.version }}
          branch: release/${{ steps.release.outputs.version }}
          commit-message: "release: bump to ${{ steps.release.outputs.version }}"
