name: Promote Release

on:
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

jobs:
  create-tag:
    name: Crate a tag based on the branch name
    if: ${{ github.event.pull_request.merged && startsWith(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version from branch
        id: branch-version
        shell: bash
        run: echo "version=${GITHUB_HEAD_REF##*\/}" >> $GITHUB_OUTPUT
