name: Release Candidate

on:
  push:
    branches:
      - "release/**"
      - "hotfix/**"

jobs:
  create-tag:
    name: Create a release candidate tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get expected base version from branch
        id: branch-version
        shell: bash
        run: echo "version=${GITHUB_REF_NAME##*\/}" >> $GITHUB_OUTPUT

      - name: Get latest version from tag
        id: tag-version
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Get current version
        id: current-version
        shell: bash
        run: |
          if [[ ${{ steps.tag-version.outputs.tag }} == ${{ steps.branch-version.outputs.version }}* ]]
          then
            echo "version=${{ steps.tag-version.outputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.branch-version.outputs.version }}-rc.0" >> $GITHUB_OUTPUT
          fi

      - name: Bump release candidate version
        id: bump-rc
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.current-version.outputs.version }}
          level: prerelease

      - name: Create bumped release candidate tag
        if: ${{ steps.bump-rc.outcome == 'success' }}
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.bump-rc.outputs.new_version }}

    outputs:
      new_version: ${{ steps.bump-rc.outputs.new_version }}

  deploy:
    name: Fake a deploy
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: Fake a deploy by sleeping
        run: sleep 5

      - name: Print result
        run: 'echo "Deployed version: ${{ needs.create-tag.outputs.new_version }}"'
